// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtnJPiuB0_OkmkOJ_rV1SlCmXU45Ad988',
    appId: '1:835797285711:web:21c4ddb1a09f4e3046e33a',
    messagingSenderId: '835797285711',
    projectId: 'machat-246a5',
    authDomain: 'machat-246a5.firebaseapp.com',
    storageBucket: 'machat-246a5.appspot.com',
    measurementId: 'G-4792K5NXZV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBShTiSCpkbv_0ZE3LEfwvzF1HuuNZzjJ4',
    appId: '1:835797285711:ios:9fd679940af5a81246e33a',
    messagingSenderId: '835797285711',
    projectId: 'machat-246a5',
    storageBucket: 'machat-246a5.appspot.com',
    iosBundleId: 'com.example.machat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBShTiSCpkbv_0ZE3LEfwvzF1HuuNZzjJ4',
    appId: '1:835797285711:ios:9fd679940af5a81246e33a',
    messagingSenderId: '835797285711',
    projectId: 'machat-246a5',
    storageBucket: 'machat-246a5.appspot.com',
    iosBundleId: 'com.example.machat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtnJPiuB0_OkmkOJ_rV1SlCmXU45Ad988',
    appId: '1:835797285711:web:96c574770682782f46e33a',
    messagingSenderId: '835797285711',
    projectId: 'machat-246a5',
    authDomain: 'machat-246a5.firebaseapp.com',
    storageBucket: 'machat-246a5.appspot.com',
    measurementId: 'G-RDLW14Y60V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAClmWl3zhveas41n6IIeUE7NQZiGxgoE',
    appId: '1:835797285711:android:74ad3d98e23f01e046e33a',
    messagingSenderId: '835797285711',
    projectId: 'machat-246a5',
    storageBucket: 'machat-246a5.appspot.com',
  );

}